### ISSUE TITLE
share the ChartQA pair distribution file

### ISSUE THREAD

**Issue by xiapengchng** [zengxingchen/ChartQA-MLLM#1]
Thank you for your excellent work on chart understanding! Could you please share the ChartQA pair distribution, as it is crucial for chart analysis? Much appreciated.

**Comment by zengxingchen** [comment]
Of course. I've updated the relevant files: [others/test_augmented_qtyped.jsonl](https://github.com/zengxingchen/ChartQA-MLLM/blob/main/others/test_augmented_qtyped.jsonl) and [others/test_human_qtyped.jsonl](https://github.com/zengxingchen/ChartQA-MLLM/blob/main/others/test_human_qtyped.jsonl). Sorry for the repo's messy directory structures. I'll update it later when I have time.

**Comment by zengxingchen** [comment]
Just check the `qtype` field of each item.
