### ISSUE TITLE
Can you upload the filtered data

### ISSUE THREAD

**Issue by xiapengchng** [zengxingchen/ChartQA-MLLM#2]
I cannot find the corresponding images in  the data_filtering/classfication/annotated-dataset-imgnames.csv. Can you upload the filtered data?

**Comment by zengxingchen** [comment]
I'm not sure what data you refer to. Annotated-dataset-imgnames.csv is the metadata of the images we collected and partially labeled for building image classifiers, while these images can be downloaded in the Google Drive link we provide, see the [README](https://github.com/zengxingchen/ChartQA-MLLM/blob/main/data_filtering/classification/README.md).
If not, are you referring to the filtered data we use for model training?

**Comment by zengxingchen** [comment]
> I'm not sure what data you refer to. Annotated-dataset-imgnames.csv is the metadata of the images we collected and partially labeled for building image classifiers, while these images can be downloaded in the Google Drive link we provide, see the [README](https://github.com/zengxingchen/ChartQA-MLLM/blob/main/data_filtering/classification/README.md). If not, are you referring to the filtered data we use for model training?

If you refer to the filtered data for the MLLM training, I will upload it before this weekend or next Monday. I will notify you in this issue~

**Comment by zengxingchen** [comment]
@xiapengchng  If you refer to images for building chart image classifiers, while these images can be downloaded in the Google Drive link we provide, see the [README](https://github.com/zengxingchen/ChartQA-MLLM/blob/main/data_filtering/classification/README.md).
Else if you refer to the filtered images for MLLM training, please refer to the [huggingface link](https://huggingface.co/datasets/lewy666/ChartInstructionData/blob/main/filtered_data_138k.zip).

**Comment by BluebirdStory** [comment]
nice job!
I have downloaded your released filtered data from huggingface (138K)，I see only two subdirs(unichart & vistext), does it mean samples from all other datasets have been all filtered out ?

**Comment by zengxingchen** [comment]
> nice job! I have downloaded your released filtered data from huggingface (138K)，I see only two subdirs(unichart & vistext), does it mean samples from all other datasets have been all filtered out ?

Hi @BluebirdStory.  The `unichart`  subdir contains the data filtered from several datasets. The reason is that we are partially based on final data collection shared by the Unichart paper. They first collected the data from several datasets and then also integreates their own data into the collection.  Therefore,  the `unichart` subdir contains several datasets, while our data statistics are based on the original dataset composition.

**Comment by BluebirdStory** [comment]
Thank you!
