### ISSUE TITLE
请问图表生成是手动还是自动的呢

### ISSUE THREAD

**Issue by pkhk-1** [zengxingchen/ChartQA-MLLM#3]
感谢您的工作！想参看您的工作生成一批中文的图表数据，看到在图表生成的代码中似乎只有图表代码的生成方案，请问最终图表图片是如何渲染得到的呢，有没有自动化方法呢，谢谢！

**Comment by zengxingchen** [comment]
Thanks for your interest. I've uploaded the scripts enabling the translation of code to png-format images. Each plot library corresponds to a unique file. Please check the `others` folder.
Generating Chinese plots is an interesting idea! If you have further questions, feel free to contact me.
